services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    env_file:
      - .env
    command: "fastapi dev src/main.py --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO__DB}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  redis_volume: